---
title: "Variable List for ASHE Proposal"
author: Olivia Morales
output: pdf_document
fontsize: 14pt
---

```{r, include=F}

library(knitr)
library(tidyverse)
library(haven)

opts_chunk$set(error = FALSE,
               echo = FALSE,
               include = TRUE,
               message = FALSE,
               warning = FALSE,
               out.width = "100%",          # figures should be as wide as margins
               comment = NA)      
```

# Table 1: Description of variables used in figures

| Name of Variable          | Description                                                                                                                 |
|:--------------------------|:----------------------------------------------------------------------------------------------------------------------------|
| sch\_deg                  | Predominant degree awarded (recoded 0s and 4s)                                                                              |
| iclevel                   | Level of the institution (2-year)                                                                                           |
| lpstafford\_amt           | Total outstanding federal Direct Loan balance                                                                               |
| creddesc                  | Text description of the level of credential                                                                                 |
| dbrr1\_fed\_ug\_rt        | Undergraduate federal student loan dollar-based 1-year repayment rate                                                       |
| pcip51                    | Percentage of degrees awarded in Health Professions and Related Programs                                                    |
| grad\_debt\_mdn10yr       | Median debt of completers expressed in 10-year monthly payments, suppressed for n=30                                        |
| age\_entry                | Average of the age of entry squared                                                                                         |
| faminc\_ind               | Average of the log of family income for independent students                                                                |
| high\_deg                 | Highest degree awarded                                                                                                      |
| lpstafford\_cnt           | Number of borrowers with outstanding federal Direct Loan balances                                                           |
| preddeg                   | Predominant undergraduate degree awarded                                                                                    |
| married                   | Share of married students                                                                                                   |
| ugds\_women               | Total share of enrollment of undergraduate degree-seeking students who are women                                            |
| md\_faminc                | Median family income in real 2015 dollars                                                                                   |
| inc\_pct\_m1              | Independent students with family incomes between $30,001-$48,000 in nominal dollars                                         |
| control                   | Control of institution, per PEPS                                                                                            |
| female                    | Percent of female students who transferred to a 2-year institution and were still enrolled within 2 years                   |
| pftftug1\_ef              | Share of entering undergraduate students who are first-time, full-time degree-/certificate-seeking undergraduate students   |
| poolyrs100                | Years used for rolling averages of completion rate C100\_[4/L4]\_POOLED                                                     |
| cdr3                      | Number of students in the cohort for the three-year cohort default rate                                                     |
| first\_gen                | Percent of first-generation students who transferred to a 2-year institution and were still enrolled within 2 years         |
| bbrr2\_fed\_ug\_          | Percentage of undergraduate federal student loan                                                                            |
| makeprog\_supp            | borrowers making progress after 2 years, suppressed for n<30                                                                |
| comp\_orig\_yr8\_rt       | Percent of students who never received a Pell Grant at the institution and who completed in 8 years at original institution |
| cdr2                      | Number of students in the cohort for the two-year cohort default rate                                                       |
| ug25abv                   | Percentage of undergraduates aged 25 and above                                                                              |
| comp\_orig\_yr3\_rt       | Percent of students who never received a Pell Grant at the institution and who completed in 3 years at original institution |
| rpy\_3yr\_rt\_supp        | 3-year repayment rate for no-Pell students, suppressed for n=30                                                             |
| ugds\_asian               | Total share of enrollment of undergraduate degree-seeking students who are Asian                                            |
| opeid6                    | 6-digit OPE ID for institution                                                                                              |
| bbrr2\_fed\_ug\_fbr\_supp | Percentage of undergraduate federal student loan borrowers in forbearance after 2 years, suppressed for n<30                |




